name: Feishu Bot

on:
  schedule:
    - cron: "20 2 * * *"   # UTC 02:10 = 北京时间 10:10

jobs:
  send-msg:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Feishu Bot
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "msg_type": "text",
              "content": { "text": "测试消息" }
            }' \
            https://open.feishu.cn/open-apis/bot/v2/hook/890a2172-a5e1-4fc3-ba88-be37cf2994e9
